inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_rspec.yml

AllCops:
  TargetRubyVersion: 2.5.5
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'bin/*'
    - 'lib/tasks/**/*'

Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
# Temporary disable, it will be fixed at last.
Style/GuardClause:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/LambdaCall:
  Enabled: false
# Temporary end
Style/SymbolProc:
  Exclude:
    - 'app/api/**/entities/*'
    - 'app/api/lms/presenter/*'

Layout/RescueEnsureAlignment:
  Enabled: false

Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Enabled: false

Metrics:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Security:
  Enabled: true
